name: spatial-heart-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - scanpy
  - squidpy
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - pip:
    - tangram-sc

